import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Bricolage_Grotesque, IBM_Plex_Mono, IBM_Plex_Sans } from "next/font/google";
// Required by MapLens (maplibre-gl): without this, marker positioning
// transforms and the map's stacking context are undefined.
import "maplibre-gl/dist/maplibre-gl.css";
import "./globals.css";
import { SaveLightProvider } from "@/components/SaveLight";
import { SITE_DESCRIPTION, SITE_NAME } from "@/lib/siteMetadata";

const display = Bricolage_Grotesque({ subsets: ["latin"], weight: ["500", "600"], variable: "--font-next-display" });
const sans = IBM_Plex_Sans({ subsets: ["latin"], weight: ["400", "500", "600"], variable: "--font-next-sans" });
const mono = IBM_Plex_Mono({ subsets: ["latin"], weight: ["400", "500"], variable: "--font-next-mono" });

// Where absolute URLs in metadata (og:image, og:url) resolve from. Vercel's
// documented hierarchy, written out rather than left to Next's default so a
// framework-version change can't silently alter what scrapers see: the
// production domain in production, the deployment's own URL on previews (so
// a shared preview link unfurls with an og:image that actually loads —
// production may not exist yet), localhost otherwise.
const metadataBase = new URL(
  process.env.VERCEL_ENV === "production" && process.env.VERCEL_PROJECT_PRODUCTION_URL
    ? `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`
    : process.env.VERCEL_URL
      ? `https://${process.env.VERCEL_URL}`
      : `http://localhost:${process.env.WEB_PORT ?? "3001"}`,
);

// og:image, og:image:alt and twitter:image come from the file conventions
// next to this layout (src/app/opengraph-image.png + .alt.txt, and icon.svg
// for the favicon — all regenerated by scripts/generate-og-assets.mjs), so
// they are deliberately not repeated here. Pages that need their own
// title/description go through lib/siteMetadata.ts's pageMetadata() — see
// the merge gotcha documented there.
export const metadata: Metadata = {
  metadataBase,
  title: { default: SITE_NAME, template: `%s — ${SITE_NAME}` },
  description: SITE_DESCRIPTION,
  openGraph: {
    siteName: SITE_NAME,
    type: "website",
    locale: "en_US",
    title: SITE_NAME,
    description: SITE_DESCRIPTION,
  },
  twitter: { card: "summary_large_image" },
};

// SPEC §28: *"`look` (not `theme` — the old key holds a stale stored value)
// defaults to **ledger**. Four looks ship: ledger, paper, nightdesk, airmail."*
//
// Written on `<html>` in the server-rendered markup rather than by an effect,
// so the first paint is already in the right look. A client-side write would
// flash the base palette — which is `paper` — on every cold load, and the
// palette is the whole of what a look is.
//
// **There is no picker yet, and that is the open question, not an oversight.**
// Whether `look` is a stored account preference is unanswered
// (`docs/plans/2026-09-12-design-sync-2026-09-12.md`): storing it means a
// column on `UserPreferences` and a migration. The token layer and the default
// do not need that answer, so they land first. When the answer arrives, this
// constant is what the resolved preference replaces, and nothing else here
// moves — every other look already works by setting the attribute.
const DEFAULT_LOOK = "ledger";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" data-look={DEFAULT_LOOK} className={`${display.variable} ${sans.variable} ${mono.variable}`}>
      <body>
        {/* Above the header AND the page, because the header's logo is the
            save light and the state it shows is published from inside the
            trip below (SaveLight.tsx). AppHeader itself no longer renders
            here — the (app) route group's own layout renders it, nested
            inside this provider — but the front door (/welcome, /signin,
            /signup) renders through this same slot with no AppHeader at all,
            so this provider wraps both: a save light with no consumer where
            there's no header, and the real one where (app)/layout.tsx
            supplies it. A client provider here does not make this layout a
            client component — `children` is still passed through as an
            already-rendered server tree. */}
        <SaveLightProvider>{children}</SaveLightProvider>
        {/* Only on Vercel. Both packages gate themselves on `isDevelopment()`
            alone, so any production build — `next start` locally, CI's
            ci-like e2e lane, a self-hosted deploy — mounted them and then
            requested `/_vercel/insights/script.js` and
            `/_vercel/speed-insights/script.js`, which only Vercel's edge ever
            serves. Off Vercel that is two 404s plus two strict-MIME refusals
            in the console on every page: 34 of the 2026-09-05 review's ~70
            browser-walk finding lines, burying real errors and making a "no
            console errors" e2e assertion impossible (KI-2026-09-05-y /
            F-G06). `VERCEL` is set by the platform on every Vercel build and
            runtime and by nothing else, which is also the condition
            next.config.ts's CSP comment already assumes when it calls these
            scripts same-origin. Read per render, not hoisted to a module
            constant, so layout.test.ts can exercise both branches. */}
        {process.env.VERCEL ? (
          <>
            <Analytics />
            <SpeedInsights />
          </>
        ) : null}
      </body>
    </html>
  );
}
