// GENERATED by apps/web/scripts/generate-og-tokens.mjs from src/app/globals.css.
// Do not edit: change globals.css and run `pnpm --filter web og:tokens`.
// `ogTokens.test.ts` fails when this file and a fresh parse disagree.

/** Brand colours as literals, for satori, which cannot resolve a CSS variable. */
export const ogColors = {
  paper: "#f7f8f6",
  surface: "#ffffff",
  moss: "#eff2ed",
  hairline: "#dde2da",
  slate: "#5a6472",
  ink: "#151d2e",
  brand: "#0e7c66",
  brandTint: "#e3f0ec",
  infoTint: "#e1ebf7",
  warningTint: "#f6ebd4",
} as const;
