import { createHash } from "node:crypto";
import { readdirSync } from "node:fs";
import path from "node:path";
import { zodToJsonSchema } from "zod-to-json-schema";
import type { z } from "zod";
import { API_SCOPES, SCOPE_CATALOGUE } from "@tc/contracts";
import { DECLARED, MAX_PAGE_LIMIT, type DeclaredHandler, type MethodDef } from "./route";
import { IDEMPOTENCY_KEY_MAX_LENGTH, REPLAYED_HEADER } from "./idempotency";

// **The reference docs, derived — never written twice** (Decision 9).
//
// Because a route's declaration is the only source, **the documentation cannot
// drift from the implementation**. That is the same "derived, never hand-written
// twice" rule as invariant 5 and ADR-015's tool schemas, and it is the single
// largest answer to *"not infinite maintenance"*: the usual second and third
// copies of an API's truth — the docs and the client — stop existing as separate
// artifacts that someone has to remember to update.
//
// **Generated by a script into a committed file, not computed per request.** A
// bundled Next server cannot walk its own source tree, and a doc built at
// request time would be a filesystem read on a hot path for something that
// changes only when the code does. `openapi.test.ts` regenerates and compares,
// so a schema changed without regenerating fails CI in the same diff that
// changed it — which is what makes "cannot drift" a fact rather than a wish.

/**
 * **The published `info.version`, and the document it was published for.**
 *
 * `info.version` sat at `"1.0.0"` through M24 (stops gained `mode` and
 * `endLocation`) and M28 (the `idea`/`hold`/`booked` kinds retired), so a
 * consumer comparing versions was told nothing had changed. The fingerprint is
 * what makes a forgotten bump a failing test instead of a reviewer's catch:
 * `openapi.test.ts` recomputes it from the generated document and fails, naming
 * the new value, when it differs from the one recorded here.
 *
 * When that test fails: bump `API_VERSION` by semver — **patch** for prose only
 * (a summary, a description, the scope text), **minor** for anything additive
 * (a new endpoint, an optional field), **major** for anything that breaks a
 * caller (a field or value removed, renamed or newly required) — then paste the
 * fingerprint the failure printed into `API_FINGERPRINT`, and add a line to
 * `docs/contracts/CHANGELOG.md`. Change both constants in the same diff.
 */
export const API_VERSION = "1.4.0";
export const API_FINGERPRINT = "1a8d3f1bc31fae2fbb830c60b087db21b5c3a93f392e8a25f82d0fd0d26b8346";

/**
 * sha256 of the document with `info.version` left out, keys sorted at every
 * level — so the fingerprint moves when the published contract does, and never
 * because of the version it is checked against or of property order.
 */
export function fingerprintOf(doc: OpenApiDocument): string {
  return createHash("sha256")
    .update(canonicalJson({ ...doc, info: { ...doc.info, version: undefined } }))
    .digest("hex");
}

function canonicalJson(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`;
  if (value !== null && typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>)
      .filter(([, v]) => v !== undefined)
      .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
    return `{${entries.map(([k, v]) => `${JSON.stringify(k)}:${canonicalJson(v)}`).join(",")}}`;
  }
  return JSON.stringify(value);
}

const HTTP_METHODS = ["GET", "POST", "PATCH", "DELETE"] as const;

/** Every `route.ts` under `v1/` — the directory IS the registry (Decision 1). */
export function routeModulePaths(v1Dir: string): string[] {
  const out: string[] = [];
  const walk = (dir: string): void => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (entry.name === "route.ts") out.push(full);
    }
  };
  walk(v1Dir);
  return out.sort();
}

/** `.../v1/trips/[tripId]/days` → `/v1/trips/{tripId}/days`. */
export function urlOf(v1Dir: string, file: string): string {
  const rel = path.relative(v1Dir, path.dirname(file)).split(path.sep).filter(Boolean);
  const segments = rel.map((s) => (s.startsWith("[") ? `{${s.slice(1, -1)}}` : s));
  return `/v1${segments.length === 0 ? "" : `/${segments.join("/")}`}`;
}

type JsonSchema = ReturnType<typeof zodToJsonSchema>;

function schemaOf(zod: z.ZodTypeAny): JsonSchema {
  // `target: "openApi3"` because zod-to-json-schema's default emits JSON Schema
  // draft-07, whose `nullable` and `exclusiveMinimum` spellings OpenAPI 3.0 does
  // not accept. zod is v3 here, which is why this library and not a v4-only one.
  return withoutTupleItems(zodToJsonSchema(zod, { target: "openApi3", $refStrategy: "none" })) as JsonSchema;
}

// **OpenAPI 3.0 has no tuples, and `openApi3` still emits one.** A `z.tuple`
// comes out as `items: [ ...schemas ]`, the draft-04 array form, where 3.0
// requires `items` to be a single Schema Object. The export bundles'
// `z.tuple([])` (`activities`, `playbooks`, `notebooks`, `trips` — "always
// empty in this file") published six `items: []`, which made the document
// invalid: Scalar's reference threw on it at `/developers/reference`, and any
// caller validating the document before trusting it would refuse it.
//
// An empty tuple becomes `items: {}`; the `maxItems: 0` beside it already says
// nothing may be there. A non-empty one **throws**, naming where it is: 3.0
// cannot say "a string, then a number", and the obvious fallback — `anyOf` the
// members — would publish a wider contract than the route accepts without
// anyone deciding to. Nothing declares one today; the day something does, the
// generator stops and the author chooses (an object, an array of one type, or
// a 3.1 document). `openapi.test.ts` also fails on an array-valued `items`
// anywhere in the published document.
/**
 * `node` with every empty tuple-form `items: []` rewritten to `items: {}`, so
 * the result is valid OpenAPI 3.0.
 *
 * @throws when it meets a non-empty tuple, with the JSON pointer of its
 * `items` in the message — 3.0 has no way to express tuple positions.
 */
export function withoutTupleItems(node: unknown, at = "#"): unknown {
  if (Array.isArray(node)) return node.map((child, i) => withoutTupleItems(child, `${at}/${i}`));
  if (node === null || typeof node !== "object") return node;
  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(node)) {
    const here = `${at}/${key.replaceAll("~", "~0").replaceAll("/", "~1")}`; // RFC 6901 escaping
    if (key === "items" && Array.isArray(value)) {
      if (value.length > 0) {
        throw new Error(
          `openapi: non-empty tuple at ${here} (${value.length} positions) — OpenAPI 3.0 cannot express tuple ` +
            `positions, and widening it to anyOf would change the contract. Declare an object or a single-type array instead.`,
        );
      }
      out[key] = {};
    } else {
      out[key] = withoutTupleItems(value, here);
    }
  }
  return out;
}

export interface OpenApiDocument {
  openapi: string;
  info: { title: string; version: string; description: string };
  paths: Record<string, Record<string, unknown>>;
  components: { securitySchemes: Record<string, unknown> };
  security: { bearerAuth: string[] }[];
}

/**
 * Build the document from the declarations themselves.
 *
 * `modules` is passed in rather than imported here so the generator script and
 * the test that checks it are running the identical walk.
 */
export function buildOpenApi(
  entries: { url: string; module: Record<string, unknown> }[],
): OpenApiDocument {
  const paths: Record<string, Record<string, unknown>> = {};

  for (const { url, module } of entries) {
    for (const method of HTTP_METHODS) {
      const handler = module[method] as DeclaredHandler | undefined;
      const declared = handler?.[DECLARED];
      if (declared === undefined) continue;
      // The declaration object itself, reached through the handler's closure is
      // not available — so the brand carries what the document needs, and the
      // schemas come from the module's own exported `route()` input via the
      // brand's `def` reference.
      const def = declared.def as MethodDef;

      const parameters: unknown[] = [];
      for (const segment of url.matchAll(/\{(\w+)\}/g)) {
        parameters.push({
          name: segment[1],
          in: "path",
          required: true,
          schema: { type: "string" },
        });
      }
      if ("collection" in def) {
        parameters.push({
          name: "limit",
          in: "query",
          required: false,
          description: `1 to ${MAX_PAGE_LIMIT}. A value outside that range is refused, never clamped.`,
          schema: { type: "integer", minimum: 1, maximum: MAX_PAGE_LIMIT },
        });
        parameters.push({
          name: "cursor",
          in: "query",
          required: false,
          description: "Opaque. Pass back the `nextCursor` of the previous page.",
          schema: { type: "string" },
        });
      }
      if (def.query !== undefined) {
        const query = schemaOf(def.query) as { properties?: Record<string, unknown>; required?: string[] };
        for (const [name, schema] of Object.entries(query.properties ?? {})) {
          parameters.push({
            name,
            in: "query",
            required: (query.required ?? []).includes(name),
            schema,
          });
        }
      }

      if (def.idempotent !== undefined) {
        parameters.push({
          name: "Idempotency-Key",
          in: "header",
          required: false,
          description:
            "Optional. A retry with the same key and the same request replays the first answer instead of " +
            "running again; the same key with a different request is a 400, and one still in progress is a " +
            "409. Kept for 24 hours, per account. A 5xx is not kept.",
          schema: { type: "string", minLength: 1, maxLength: IDEMPOTENCY_KEY_MAX_LENGTH },
        });
      }

      const responseHeaders = {
        ...def.responseHeaders,
        ...(def.idempotent === undefined
          ? {}
          : { [REPLAYED_HEADER]: "`true` when this answer is a replay of an earlier request with the same Idempotency-Key." }),
      };

      const responseSchema =
        "collection" in def
          ? {
              type: "object",
              required: ["items", "nextCursor"],
              properties: {
                items: { type: "array", items: schemaOf(def.collection.item) },
                nextCursor: { type: "string", nullable: true },
              },
            }
          : schemaOf((def as { response: z.ZodTypeAny }).response);

      const status = def.status ?? (method === "POST" ? 201 : 200);
      paths[url] ??= {};
      paths[url]![method.toLowerCase()] = {
        summary: def.summary,
        description: [
          `Requires the \`${declared.scope}\` scope.`,
          declared.role === undefined
            ? undefined
            : declared.trip === "path"
              ? `Requires at least the \`${declared.role}\` role on the trip.`
              : `Requires at least the \`${declared.role}\` role on the trip the body names, if it names one.`,
          def.description,
        ]
          .filter(Boolean)
          .join(" "),
        security: [{ bearerAuth: [declared.scope] }],
        ...(parameters.length === 0 ? {} : { parameters }),
        ...(def.body === undefined
          ? {}
          : {
              requestBody: {
                required: true,
                content: { "application/json": { schema: schemaOf(def.body) } },
              },
            }),
        responses: {
          [String(status)]: {
            description: "Success.",
            ...(Object.keys(responseHeaders).length === 0
              ? {}
              : {
                  headers: Object.fromEntries(
                    Object.entries(responseHeaders).map(([name, description]) => [
                      name,
                      { description, schema: { type: "string" } },
                    ]),
                  ),
                }),
            content: { "application/json": { schema: responseSchema } },
          },
          "4XX": {
            description:
              "One envelope for every failure: `{ error: { code, message, details? } }`. " +
              "401 carries `WWW-Authenticate: Bearer`; 429 carries `Retry-After`.",
          },
        },
      };
    }
  }

  return {
    openapi: "3.0.3",
    info: {
      title: "Caesura API",
      version: API_VERSION,
      description: [
        "The public REST API. Every endpoint takes an account API token as",
        "`Authorization: Bearer tc_...`, minted in Account settings.",
        "",
        "Scopes:",
        ...API_SCOPES.map((scope) => `- \`${scope}\` — ${SCOPE_CATALOGUE[scope].description}`),
      ].join("\n"),
    },
    paths,
    components: {
      securitySchemes: {
        bearerAuth: { type: "http", scheme: "bearer", bearerFormat: "tc_<base64url>" },
      },
    },
    security: [{ bearerAuth: [] }],
  };
}
