import { readdirSync } from "node:fs";
import path from "node:path";
import { zodToJsonSchema } from "zod-to-json-schema";
import type { z } from "zod";
import { API_SCOPES, SCOPE_CATALOGUE } from "@tc/contracts";
import { DECLARED, MAX_PAGE_LIMIT, type DeclaredHandler, type MethodDef } from "./route";
import { IDEMPOTENCY_KEY_MAX_LENGTH, REPLAYED_HEADER } from "./idempotency";

// **The reference docs, derived — never written twice** (Decision 9).
//
// Because a route's declaration is the only source, **the documentation cannot
// drift from the implementation**. That is the same "derived, never hand-written
// twice" rule as invariant 5 and ADR-015's tool schemas, and it is the single
// largest answer to *"not infinite maintenance"*: the usual second and third
// copies of an API's truth — the docs and the client — stop existing as separate
// artifacts that someone has to remember to update.
//
// **Generated by a script into a committed file, not computed per request.** A
// bundled Next server cannot walk its own source tree, and a doc built at
// request time would be a filesystem read on a hot path for something that
// changes only when the code does. `openapi.test.ts` regenerates and compares,
// so a schema changed without regenerating fails CI in the same diff that
// changed it — which is what makes "cannot drift" a fact rather than a wish.

const HTTP_METHODS = ["GET", "POST", "PATCH", "DELETE"] as const;

/** Every `route.ts` under `v1/` — the directory IS the registry (Decision 1). */
export function routeModulePaths(v1Dir: string): string[] {
  const out: string[] = [];
  const walk = (dir: string): void => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (entry.name === "route.ts") out.push(full);
    }
  };
  walk(v1Dir);
  return out.sort();
}

/** `.../v1/trips/[tripId]/days` → `/v1/trips/{tripId}/days`. */
export function urlOf(v1Dir: string, file: string): string {
  const rel = path.relative(v1Dir, path.dirname(file)).split(path.sep).filter(Boolean);
  const segments = rel.map((s) => (s.startsWith("[") ? `{${s.slice(1, -1)}}` : s));
  return `/v1${segments.length === 0 ? "" : `/${segments.join("/")}`}`;
}

type JsonSchema = ReturnType<typeof zodToJsonSchema>;

function schemaOf(zod: z.ZodTypeAny): JsonSchema {
  // `target: "openApi3"` because zod-to-json-schema's default emits JSON Schema
  // draft-07, whose `nullable` and `exclusiveMinimum` spellings OpenAPI 3.0 does
  // not accept. zod is v3 here, which is why this library and not a v4-only one.
  return zodToJsonSchema(zod, { target: "openApi3", $refStrategy: "none" });
}

export interface OpenApiDocument {
  openapi: string;
  info: { title: string; version: string; description: string };
  paths: Record<string, Record<string, unknown>>;
  components: { securitySchemes: Record<string, unknown> };
  security: { bearerAuth: string[] }[];
}

/**
 * Build the document from the declarations themselves.
 *
 * `modules` is passed in rather than imported here so the generator script and
 * the test that checks it are running the identical walk.
 */
export function buildOpenApi(
  entries: { url: string; module: Record<string, unknown> }[],
): OpenApiDocument {
  const paths: Record<string, Record<string, unknown>> = {};

  for (const { url, module } of entries) {
    for (const method of HTTP_METHODS) {
      const handler = module[method] as DeclaredHandler | undefined;
      const declared = handler?.[DECLARED];
      if (declared === undefined) continue;
      // The declaration object itself, reached through the handler's closure is
      // not available — so the brand carries what the document needs, and the
      // schemas come from the module's own exported `route()` input via the
      // brand's `def` reference.
      const def = declared.def as MethodDef;

      const parameters: unknown[] = [];
      for (const segment of url.matchAll(/\{(\w+)\}/g)) {
        parameters.push({
          name: segment[1],
          in: "path",
          required: true,
          schema: { type: "string" },
        });
      }
      if ("collection" in def) {
        parameters.push({
          name: "limit",
          in: "query",
          required: false,
          description: `1 to ${MAX_PAGE_LIMIT}. A value outside that range is refused, never clamped.`,
          schema: { type: "integer", minimum: 1, maximum: MAX_PAGE_LIMIT },
        });
        parameters.push({
          name: "cursor",
          in: "query",
          required: false,
          description: "Opaque. Pass back the `nextCursor` of the previous page.",
          schema: { type: "string" },
        });
      }
      if (def.query !== undefined) {
        const query = schemaOf(def.query) as { properties?: Record<string, unknown>; required?: string[] };
        for (const [name, schema] of Object.entries(query.properties ?? {})) {
          parameters.push({
            name,
            in: "query",
            required: (query.required ?? []).includes(name),
            schema,
          });
        }
      }

      if (def.idempotent !== undefined) {
        parameters.push({
          name: "Idempotency-Key",
          in: "header",
          required: false,
          description:
            "Optional. A retry with the same key and the same request replays the first answer instead of " +
            "running again; the same key with a different request is a 400, and one still in progress is a " +
            "409. Kept for 24 hours, per account. A 5xx is not kept.",
          schema: { type: "string", minLength: 1, maxLength: IDEMPOTENCY_KEY_MAX_LENGTH },
        });
      }

      const responseHeaders = {
        ...def.responseHeaders,
        ...(def.idempotent === undefined
          ? {}
          : { [REPLAYED_HEADER]: "`true` when this answer is a replay of an earlier request with the same Idempotency-Key." }),
      };

      const responseSchema =
        "collection" in def
          ? {
              type: "object",
              required: ["items", "nextCursor"],
              properties: {
                items: { type: "array", items: schemaOf(def.collection.item) },
                nextCursor: { type: "string", nullable: true },
              },
            }
          : schemaOf((def as { response: z.ZodTypeAny }).response);

      const status = def.status ?? (method === "POST" ? 201 : 200);
      paths[url] ??= {};
      paths[url]![method.toLowerCase()] = {
        summary: def.summary,
        description: [
          `Requires the \`${declared.scope}\` scope.`,
          declared.role === undefined
            ? undefined
            : `Requires at least the \`${declared.role}\` role on the trip.`,
        ]
          .filter(Boolean)
          .join(" "),
        security: [{ bearerAuth: [declared.scope] }],
        ...(parameters.length === 0 ? {} : { parameters }),
        ...(def.body === undefined
          ? {}
          : {
              requestBody: {
                required: true,
                content: { "application/json": { schema: schemaOf(def.body) } },
              },
            }),
        responses: {
          [String(status)]: {
            description: "Success.",
            ...(Object.keys(responseHeaders).length === 0
              ? {}
              : {
                  headers: Object.fromEntries(
                    Object.entries(responseHeaders).map(([name, description]) => [
                      name,
                      { description, schema: { type: "string" } },
                    ]),
                  ),
                }),
            content: { "application/json": { schema: responseSchema } },
          },
          "4XX": {
            description:
              "One envelope for every failure: `{ error: { code, message, details? } }`. " +
              "401 carries `WWW-Authenticate: Bearer`; 429 carries `Retry-After`.",
          },
        },
      };
    }
  }

  return {
    openapi: "3.0.3",
    info: {
      title: "Caesura API",
      version: "1.0.0",
      description: [
        "The public REST API. Every endpoint takes an account API token as",
        "`Authorization: Bearer tc_...`, minted in Account settings.",
        "",
        "Scopes:",
        ...API_SCOPES.map((scope) => `- \`${scope}\` — ${SCOPE_CATALOGUE[scope].description}`),
      ].join("\n"),
    },
    paths,
    components: {
      securitySchemes: {
        bearerAuth: { type: "http", scheme: "bearer", bearerFormat: "tc_<base64url>" },
      },
    },
    security: [{ bearerAuth: [] }],
  };
}
