-- `users.time_format` — whether this person reads clock times as 12-hour
-- ("2:30 pm") or 24-hour ("14:30"). Mitchell's ask: 12-hour stays the
-- default, 24-hour is a setting.
--
-- NOT NULL DEFAULT '12h', the same shape as `distance_unit` (0015): the
-- preference has no unset state, so every existing row reads as 12-hour — what
-- it rendered before the column existed.
--
-- IF NOT EXISTS because the shared preview database already has this column:
-- an earlier cut of this change (the pre-reset PR #225) applied its own 0031
-- there under an older journal `when`, so drizzle runs this one again and a
-- bare ADD COLUMN failed the preview build. On a database that has never seen
-- it — production included — the statement is exactly the bare one.
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "time_format" text DEFAULT '12h' NOT NULL;
