// The one parser that lifts brand colours out of `src/app/globals.css` for the
// two surfaces that cannot read a CSS custom property: the committed static
// card (`generate-og-assets.mjs`, rendered by Playwright into a PNG) and the
// per-link cards (`src/server/og/`, rendered by satori, which has no
// `var(--…)`). Two parsers would drift; this is the single copy. A third
// surface joined in M39: the web app manifest and the `theme-color` meta
// (`src/lib/appColors.generated.ts`), which a browser reads as literals.
//
// Pure: every function takes the stylesheet's text and returns strings, so the
// verify test can run the same code over the same input and compare.

/** The tokens the cards use, keyed by the name the generated module exports. */
export const OG_COLOR_TOKENS = {
  paper: "paper",
  surface: "surface",
  moss: "moss",
  hairline: "hairline",
  slate: "slate",
  ink: "ink",
  brand: "brand",
  brandTint: "brand-tint",
  infoTint: "info-tint",
  warningTint: "warning-tint",
};

/**
 * The hex value of `--color-<name>` in `css` — the FIRST declaration, which is
 * the `@theme` default rather than the ledger look's override further down.
 * Throws when the token is missing, so a rename fails the generator loudly.
 */
export function colorToken(css, name) {
  const m = css.match(new RegExp(`--color-${name}:\\s*(#[0-9a-fA-F]{3,8})\\b`));
  if (!m) throw new Error(`token --color-${name} not found in globals.css`);
  return m[1];
}

/** Every token in `OG_COLOR_TOKENS`, resolved against `css`. */
export function readOgColors(css) {
  return Object.fromEntries(Object.entries(OG_COLOR_TOKENS).map(([key, name]) => [key, colorToken(css, name)]));
}

/** The exact source of `src/server/og/ogTokens.generated.ts` for this `css`. */
export function renderOgTokensModule(css) {
  const colors = readOgColors(css);
  const lines = Object.entries(colors).map(([key, value]) => `  ${key}: "${value}",`);
  return [
    "// GENERATED by apps/web/scripts/generate-og-tokens.mjs from src/app/globals.css.",
    "// Do not edit: change globals.css and run `pnpm --filter web og:tokens`.",
    "// `ogTokens.test.ts` fails when this file and a fresh parse disagree.",
    "",
    "/** Brand colours as literals, for satori, which cannot resolve a CSS variable. */",
    "export const ogColors = {",
    ...lines,
    "} as const;",
    "",
  ].join("\n");
}

/**
 * The hex value of `--color-<name>` inside the `html[data-look="ledger"]` block:
 * what the app actually paints, where `colorToken` reads the `@theme` fallback
 * the OG assets were drawn from. Throws when the block or the token is missing.
 */
export function ledgerColorToken(css, name) {
  const open = css.indexOf('html[data-look="ledger"] {');
  if (open === -1) throw new Error("the ledger look's block was not found in globals.css");
  const body = css.slice(open, css.indexOf("\n}", open));
  const m = body.match(new RegExp(`--color-${name}:\\s*(#[0-9a-fA-F]{3,8})\\b`));
  if (!m) throw new Error(`token --color-${name} not found in the ledger look`);
  return m[1];
}

/**
 * The exact source of `src/lib/appColors.generated.ts` for this `css`: the two
 * colours the installed app's chrome takes from the page (M39). `surface` is
 * AppHeader's background, so the OS bar above it meets it without a seam;
 * `paper` is the body's, so the splash screen is the colour the first paint is.
 */
export function renderAppColorsModule(css) {
  return [
    "// GENERATED by apps/web/scripts/generate-og-tokens.mjs from src/app/globals.css.",
    "// Do not edit: change globals.css and run `pnpm --filter web og:tokens`.",
    "// `appColors.test.ts` fails when this file and a fresh parse disagree.",
    "",
    "/** The Ledger look's chrome colours as literals, for the manifest and `theme-color`. */",
    "export const appColors = {",
    `  surface: "${ledgerColorToken(css, "surface")}",`,
    `  paper: "${ledgerColorToken(css, "paper")}",`,
    "} as const;",
    "",
  ].join("\n");
}
