// The one parser that lifts brand colours out of `src/app/globals.css` for the
// two surfaces that cannot read a CSS custom property: the committed static
// card (`generate-og-assets.mjs`, rendered by Playwright into a PNG) and the
// per-link cards (`src/server/og/`, rendered by satori, which has no
// `var(--…)`). Two parsers would drift; this is the single copy.
//
// Pure: every function takes the stylesheet's text and returns strings, so the
// verify test can run the same code over the same input and compare.

/** The tokens the cards use, keyed by the name the generated module exports. */
export const OG_COLOR_TOKENS = {
  paper: "paper",
  surface: "surface",
  moss: "moss",
  hairline: "hairline",
  slate: "slate",
  ink: "ink",
  brand: "brand",
  brandTint: "brand-tint",
  infoTint: "info-tint",
  warningTint: "warning-tint",
};

/**
 * The hex value of `--color-<name>` in `css` — the FIRST declaration, which is
 * the `@theme` default rather than the ledger look's override further down.
 * Throws when the token is missing, so a rename fails the generator loudly.
 */
export function colorToken(css, name) {
  const m = css.match(new RegExp(`--color-${name}:\\s*(#[0-9a-fA-F]{3,8})\\b`));
  if (!m) throw new Error(`token --color-${name} not found in globals.css`);
  return m[1];
}

/** Every token in `OG_COLOR_TOKENS`, resolved against `css`. */
export function readOgColors(css) {
  return Object.fromEntries(Object.entries(OG_COLOR_TOKENS).map(([key, name]) => [key, colorToken(css, name)]));
}

/** The exact source of `src/server/og/ogTokens.generated.ts` for this `css`. */
export function renderOgTokensModule(css) {
  const colors = readOgColors(css);
  const lines = Object.entries(colors).map(([key, value]) => `  ${key}: "${value}",`);
  return [
    "// GENERATED by apps/web/scripts/generate-og-tokens.mjs from src/app/globals.css.",
    "// Do not edit: change globals.css and run `pnpm --filter web og:tokens`.",
    "// `ogTokens.test.ts` fails when this file and a fresh parse disagree.",
    "",
    "/** Brand colours as literals, for satori, which cannot resolve a CSS variable. */",
    "export const ogColors = {",
    ...lines,
    "} as const;",
    "",
  ].join("\n");
}
