// The v2 golden document (ADR-038 decision 5): the SAME page as
// `pageDocV1.ts`, stored the way this build stores it — every widget named for
// the primitive it is, every filter under the dimension's own name, and `v: 2`
// present because a v2 row carries one.
//
// It sits beside the v1 golden rather than replacing it, which is the thing the
// v1 file's own header said would happen: *"this file is frozen the day a v2
// fixture sits beside it"*. Between them they answer two different questions,
// and mixing them made one test answer neither:
//
//   * the v1 golden is what a MIGRATION is tested against — a real v1 row,
//     rewritten, compared to this;
//   * this one is what ROUND-TRIPPING is tested against — parse, serialise,
//     compare, with no migration in the middle to move the goalposts.
//
// **It is the v1 golden with the four widget names rewritten by hand, from
// ADR-039's spec §4 table.** Deliberately NOT produced by running
// `migratePageDoc` over the v1 golden: a golden generated by the code it guards
// agrees with that code by construction and catches nothing. Keeping the rest
// of the document character-identical to v1 is the point — the migration must
// touch widget names and nothing else, and a diff between these two files is
// the readable statement of that.
export const PAGE_DOC_V2_GOLDEN: unknown = {
  v: 2,
  type: "doc",
  content: [
    { type: "heading", attrs: { level: 1 }, content: [{ type: "text", text: "Kyoto" }] },
    {
      type: "paragraph",
      content: [
        { type: "text", text: "Total so far: " },
        { type: "macro", attrs: { name: "cost", params: {} } },
        { type: "text", text: " (rough)", marks: [{ type: "italic" }] },
      ],
    },
    { type: "heading", attrs: { level: 2 }, content: [{ type: "text", text: "Day 3" }] },
    { type: "macro", attrs: { name: "day.detail", params: { day: { kind: "index", index: 2 } } } },
    { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "Notes" }] },
    { type: "paragraph", content: [{ type: "text", text: "Book the ryokan.", marks: [{ type: "bold" }] }] },
    { type: "paragraph" },
    {
      type: "repeat",
      attrs: { name: "day.rows", params: { day: { kind: "index", index: 0 } } },
      content: [{ type: "text", text: "· " }, { type: "macro", attrs: { name: "cost", params: {} } }],
    },
    // Levels 4-6 are reachable from the editor and from `/ask`; the AST said
    // 1-3 until 2026-09-03, which made this heading a hard parse error.
    { type: "heading", attrs: { level: 6 }, content: [{ type: "text", text: "Small print" }] },
    // A list whose second item nests another list — the depth at which a
    // serialiser that walks only one level starts losing things.
    {
      type: "bulletList",
      content: [
        { type: "listItem", content: [{ type: "paragraph", content: [{ type: "text", text: "Passport" }] }] },
        {
          type: "listItem",
          content: [
            { type: "paragraph", content: [{ type: "text", text: "Money" }] },
            {
              type: "bulletList",
              content: [
                {
                  type: "listItem",
                  content: [
                    {
                      type: "paragraph",
                      content: [
                        { type: "text", text: "budget " },
                        { type: "macro", attrs: { name: "cost", params: {} } },
                      ],
                    },
                    // Two levels of list down, beside a widget: the deepest
                    // point at which decision 3 has to still be true, and the
                    // one a serialiser that walks a single level gets wrong.
                    { type: "checklist", attrs: { done: false }, content: [] },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: "orderedList",
      attrs: { start: 3, type: null },
      content: [
        { type: "listItem", content: [{ type: "paragraph", content: [{ type: "text", text: "Third, then." }] }] },
      ],
    },
    {
      type: "blockquote",
      content: [
        { type: "paragraph", content: [{ type: "text", text: "Nothing is ever booked until it is paid for." }] },
        {
          type: "bulletList",
          content: [
            {
              type: "listItem",
              content: [
                { type: "paragraph", content: [{ type: "text", text: "even this one" }] },
                // A node from a newer build, four levels down. Decision 3 has
                // to hold here too, or the nesting is where it quietly stops.
                { type: "poll", attrs: { question: "ryokan or hotel?" }, content: [] },
              ],
            },
          ],
        },
      ],
    },
    { type: "codeBlock", attrs: { language: "ts" }, content: [{ type: "text", text: "const nights = 4;" }] },
    { type: "horizontalRule" },
    {
      type: "paragraph",
      content: [
        { type: "text", text: "Depart 09:40" },
        { type: "hardBreak" },
        { type: "text", text: "Arrive 12:15" },
      ],
    },
    // A node written by a build newer than this one. A v1 row can contain one
    // the day after a deploy, and it has to survive being read by this build.
    { type: "timeline", attrs: { zoom: "week" }, content: [{ type: "text", text: "held verbatim" }] },
  ],
};
