// GENERATED by apps/web/scripts/generate-og-tokens.mjs from src/app/globals.css.
// Do not edit: change globals.css and run `pnpm --filter web og:tokens`.
// `appColors.test.ts` fails when this file and a fresh parse disagree.

/** The Ledger look's chrome colours as literals, for the manifest and `theme-color`. */
export const appColors = {
  surface: "#ffffff",
  paper: "#faf8f3",
} as const;
